// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjHhbAI-rIB1_JFTXMwPG2l063wuD__vg',
    appId: '1:270057436415:web:a9a530f534c917206508ca',
    messagingSenderId: '270057436415',
    projectId: 'xpert-autism-27df9',
    authDomain: 'xpert-autism-27df9.firebaseapp.com',
    storageBucket: 'xpert-autism-27df9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_xljVdUAvoQiQMFVL8cDJL013ALXN6mI',
    appId: '1:270057436415:android:9357a5e9d2db7e9c6508ca',
    messagingSenderId: '270057436415',
    projectId: 'xpert-autism-27df9',
    storageBucket: 'xpert-autism-27df9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHbgV4otr0ULylEkCKoK6cqEQa1ZbgmT8',
    appId: '1:270057436415:ios:41a6ed6d56cf41f16508ca',
    messagingSenderId: '270057436415',
    projectId: 'xpert-autism-27df9',
    storageBucket: 'xpert-autism-27df9.appspot.com',
    iosBundleId: 'com.example.xpertAutism',
  );
}
